#ifndef FIRMWARE_SETTINGS_H
#define FIRMWARE_SETTINGS_H

#define MOTOR0_NODEID 0x01
#define MOTOR1_NODEID 0x02

#define DEFAULT_COMMAND_TIMEOUT 1000.0f
#define DEFAULT_ENCODER_ZERO 0.0f
#define DEFAULT_AXIS_OFFSET 0.0f
#define DEFAULT_PPID_Kp 1.0f
#define DEFAULT_PPID_Ki 0.0f
#define DEFAULT_PPID_Kd 0.00f
#define DEFAULT_PPID_Kaw 0.0f
#define DEFAULT_PPID_deadzone 0.0f
#define DEFAULT_PPID_Umax 1000.0f
#define DEFAULT_PPID_dUmax 1000.0f
#define DEFAULT_VPID_Kp 1.0f
#define DEFAULT_VPID_Ki 0.0f
#define DEFAULT_VPID_Kd 0.0f
#define DEFAULT_VPID_Kaw 0.0f
#define DEFAULT_VPID_deadzone 0.0f
#define DEFAULT_VPID_Umax 1000.0f
#define DEFAULT_VPID_dUmax 1000.0f
#define DEFAULT_CPID_Kp 1.0f
#define DEFAULT_CPID_Ki 0.0f
#define DEFAULT_CPID_Kd 0.00f
#define DEFAULT_CPID_Kaw 0.0f
#define DEFAULT_CPID_deadzone 0.0f
#define DEFAULT_CPID_Umax 1000.0f
#define DEFAULT_CPID_dUmax 1000.0f
#define DEFAULT_IIR_VALUE_CURMEAS 0.0f
#define DEFAULT_IIR_VALUE_VELMEAS 0.0f
#define DEFAULT_IIR_VALUE_PPIDU 0.0f
#define DEFAULT_IIR_VALUE_VPIDU 0.0f
#define DEFAULT_IIR_VALUE_CPIDU 0.0f
#define DEFAULT_VELFeedForward_GAIN 0.0f
#define DEFAULT_ACCFeedForward_GAIN 0.0f
#define DEFAULT_MIN_POSITION -1000000.0f
#define DEFAULT_MAX_POSITION 1000000.0f
#define DEFAULT_MIN_VELOCITY -100.0f
#define DEFAULT_MAX_VELOCITY 100.0f
#define DEFAULT_MIN_CURRENT -10.0f
#define DEFAULT_MAX_CURRENT 10.0f
#define DEFAULT_MIN_DUTY -1.0f
#define DEFAULT_MAX_DUTY 1.0f
#define DEFAULT_OVERHEAT_TEMPERATURE 75.0f
#define DEFAULT_NO_OVERHEAT_TEMPERATURE 65.0f
#define DEFAULT_INVERT_AXIS 0
#define DEFAULT_INVERT_ENCODER 0
#define DEFAULT_ENCODER_FILTER_WINDOW 1.024f

#endif // FIRMWARE_SETTINGS_H